feat(new-ai-vertical-routes): new routes ai vertical
freepik-company/api-specs pull request #18
Opened 2023-05-24 12:57 UTC by lope7

New routes AI vertical: detail and popular.

2023-05-24 14:29 UTC, jlaupa requested changes

2023-05-24 14:29 UTC, jlaupa commented on ai/aigenerated-openapi.yaml
> +  /v1/ai/{id}:
para el response del detalle creo que podemos mejorar el

```
ai_metadata: {
   "model_type": "Midjourney",
   "model_subtype": "niji",
   "has_prompt": true 
}
```
```
  "model_type": "Midjourney",
  "model_subtype": "niji",
  "has_prompt": true
```

2023-05-24 14:41 UTC, jlaupa commented on ai/aigenerated-openapi.yaml
> +  /v1/ai/{id}:
cc: @Muriano @pablodnl22 @isa-gdt

2023-05-24 14:44 UTC, lope7 commented on ai/aigenerated-openapi.yaml
> +  /v1/ai/{id}:
done

2023-05-25 06:51 UTC, jlaupa approved these changes

2023-05-25 07:42 UTC, merged