Feature/ovi 199 filer fps
freepik-company/api-specs pull request #5
Opened 2023-05-18 06:08 UTC by mhbandres

Add schema `FilterFps` to represent different possible fps values: 24, 25, 30, 50, 60 and gt60 (greater than 60) as described in the [Jira issue](https://freepikcompany.atlassian.net/browse/OVI-326)

2023-05-18 06:18 UTC, jlaupa requested changes

2023-05-18 06:18 UTC, jlaupa commented on videos/videos-openapi.yaml
> +        - '24', '25', '30', '50', '60', 'gt60'
Eliminaria el "Possible values:        - '24', '25', '30', '50', '60', 'gt60'" ya el enum te da los posibles valores en la definición.

2023-05-19 06:05 UTC, pablodnl22 approved these changes

2023-05-19 06:07 UTC, jlaupa commented on videos/videos-openapi.yaml
> +            example: "[ 4:3 ]"
Sin comillas da error.

2023-05-19 06:13 UTC, jlaupa approved these changes

2023-05-19 06:14 UTC, merged