Feature/ovi 200 filer category video
freepik-company/api-specs pull request #9
Opened 2023-05-22 09:28 UTC by mhbandres

Add filter for topics [as indicated in this jira issue](https://freepikcompany.atlassian.net/browse/OVI-329)

2023-05-22 10:14 UTC, isa-gdt approved these changes

2023-05-22 10:47 UTC, mhbandres commented on videos/videos-openapi.yaml
> +      description: Filter by Topic.
en la tarjeta viene que se debe llamar theme, pero luego pone topic...

2023-05-23 14:50 UTC, jlaupa requested changes

2023-05-23 14:50 UTC, jlaupa commented on videos/videos-openapi.yaml
> +    FilterTopic:
FilterTopic por FilterTheme, no?

2023-05-24 08:13 UTC, jlaupa approved these changes

2023-05-24 08:15 UTC, mhbandres commented on videos/videos-openapi.yaml
> +    FilterTopic:
zi

2023-05-24 08:30 UTC, merged